baseURL = 'gerdm.github.io'
languageCode = 'en-us'
title = 'Gerardo Duran-Martin'
theme = "archie"

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[services]
  [services.googleAnalytics]
    ID = "G-F409TRWCXC"

[params]
	customcss = ["css/first.css"]
	mode = "light"
	useCDN = false
	subtitle = "Maths and machines"


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gerdm"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/grrddm/"

[[params.social]]
name = "Twitter"
icon = "linkedin"
url = "https://linkedin.com/in/grrddm/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CV"
url = "/cv"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
